name: Pytest with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    environment: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests with coverage
        env:
          DB_URL: ${{ vars.DB_URL }}
          CLD_API_KEY: ${{ vars.CLD_API_KEY }}
          CLD_API_SECRET: ${{ vars.CLD_API_SECRET }}
          CLD_NAME: ${{ vars.CLD_NAME }}
          JWT_SECRET: ${{ vars.JWT_SECRET }}
          MAIL_FROM: ${{ vars.MAIL_FROM }}
          MAIL_PASSWORD: ${{ vars.MAIL_PASSWORD }}
          MAIL_USERNAME: ${{ vars.MAIL_USERNAME }}
        run: |
          poetry run pytest --cov=src --cov-report=xml --cov-report=term

      - name: Update README with Coverage Badge
        env:
          COVERAGE: ${{ steps.coverage.outputs.coverage }}
        run: |
          COVERAGE_PERCENT=$(grep -oP '(?<=line-rate="[0-9]+\.[0-9]+")' coverage.xml | awk '{print int($1 * 100)}')
          sed -i '/^\!\[Coverage\](.*)/c\![Coverage](https://img.shields.io/badge/Coverage-'${COVERAGE_PERCENT}'%25-brightgreen)' README.md

      - name: Commit updated README
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add README.md
          git commit -m "Update coverage badge"
          git push
